package params

import "math"

// ---------------------------------------------------------------------------
// Summoning Sign params — NET_SUMMON_SIGN_PARAM + NET_COMMON_PARAM
// 12 params: 7 basic (matching SaveForge), 5 advanced (not edited by SaveForge).
// Basic sorted: refresh rate, pool params (total/cell/cap), sync timing.
// ---------------------------------------------------------------------------

var signParams = []ParamMeta{
	{
		Key: "reloadSignIntervalTime2", View: ViewSign,
		Label: "Sign refresh interval", Internal: "ReloadSignIntervalTime2", Type: "float32",
		Advanced: false, Min: 5, Max: 120, UnlockMin: 1, UnlockMax: 999,
		ShortDef: "Full cache invalidation cadence during active play. At each interval the client discards its local sign list entirely and downloads a fresh copy from the server.\r\nRaise → signs grow stale; new placements appear late, expired ones linger.\r\nLower → sign pool stays current; recent placements and removals are reflected faster.",
		LongDef: "Summon signs — the golden and red marks you see on the ground — are not streamed to your game in real time. Your game periodically downloads a snapshot of available signs from the server, stores that snapshot locally, and displays those stored signs on the ground. Between downloads, the signs you see are whatever was in the last snapshot, even if the actual situation has changed.\r\n\r\nThis parameter controls how often that snapshot is completely replaced during normal play — while you are walking through an area, standing near signs, or approaching a boss fog gate. At the game's default of 60 seconds, a phantom who placed a sign immediately after your last download will not appear for you until the next one — potentially nearly a full minute later. At the same time, a sign from a phantom who was already summoned or disconnected may remain visible on your screen until that refresh clears it.\r\n\r\nReducing this value makes those refreshes happen more often, keeping the signs you see much closer to the server's current state. At 10–15 seconds, new signs show up shortly after being placed and expired ones disappear promptly, which makes the co-op experience feel significantly more alive and responsive.\r\n\r\nRaising it beyond 60 seconds is workable in quiet areas with little sign activity, but creates a noticeably stale and confusing experience in busy co-op zones.",
		AdvancedDetails: "PARAMDEF SortID: 103 — 召喚サイン再取得待機時間[秒] (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x1C  |  Type: float32\r\nVanilla value: 60 s\r\nValidation: 1–1000 s\r\nThis is the 'active' refresh timer. The companion 'inactive' timer (SortID 102, Inactive Refresh Interval) is at offset 0x18 and is an Advanced parameter.",
	},
	{
		Key: "reloadSignTotalCount", View: ViewSign,
		Label: "Sign pool (total)", Internal: "ReloadSignTotalCount", Type: "int32",
		Advanced: false, Min: 5, Max: 64, UnlockMin: 1, UnlockMax: float64(math.MaxInt32),
		Warning: "Must satisfy the invariant: Sign Pool (Per Cell) ≤ Sign Pool (Total) ≤ Sign Buffer Cap. Violating it produces inconsistent pool behaviour.",
		ShortDef: "Client-side cache capacity after each refresh — the maximum number of signs stored and displayed simultaneously. Does not affect how many the server holds, only how many the client stores.\r\nRaise → more signs visible at once; essential in high-density areas where 20 hides most available phantoms.\r\nLower → smaller local pool; limits visible signs regardless of how many the server has.",
		LongDef: "When your game downloads the sign snapshot from the server, it does not show you every sign the server knows about. It only stores and displays up to this many signs at a time.\r\n\r\nAt the default of 20, you see at most 20 signs on the ground simultaneously. In popular co-op areas — just before a major boss fog gate, for example — the server may have 50, 100, or more active signs from players waiting to be summoned. Your game shows you only 20 of them, hiding the rest entirely.\r\n\r\nRaising this value simply increases how many signs your game holds in its local cache after each refresh. You are not making additional server requests — you are asking for a bigger slice of the available signs each time. The improvement is most noticeable in high-activity areas where the default of 20 creates a misleadingly thin-looking sign pool.\r\n\r\nThis value must be at least as large as Sign Pool (Per Cell), and must not exceed Sign Buffer Cap. See the Warning above.",
		AdvancedDetails: "PARAMDEF SortID: 105 — 召喚サイン所持可能数上限(全体) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x20  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 20\r\nValidation: 1–128\r\nCross-field constraints: must be ≥ ReloadSignCellCount (0x24) and ≤ SingGetMax (0x60). Breaking these invariants produces inconsistent pool behavior.",
	},
	{
		Key: "reloadSignCellCount", View: ViewSign,
		Label: "Sign pool (per cell)", Internal: "ReloadSignCellCount", Type: "int32",
		Advanced: false, Min: 1, Max: 32, UnlockMin: 1, UnlockMax: 99,
		Warning: "Must not exceed Sign Pool (Total). ValidateNetworkParams enforces this constraint.",
		ShortDef: "Per-zone contribution cap within the total pool. Prevents a single dense cell from monopolising the entire cache by limiting how many signs the client accepts from any one spatial zone.\r\nRaise → dense zones can supply a larger share of the pool; reduces geographic diversity.\r\nLower → caps each zone's contribution; forces broader geographic spread across the pool.",
		LongDef: "The game world is divided into an invisible spatial grid of zones for multiplayer matchmaking. When your game collects signs to fill its local pool, it gathers them from all the zones around your current position. Without any restriction, one extremely popular zone — the approach to a famous boss, for instance — could fill your entire sign pool by itself, leaving nothing from any surrounding area.\r\n\r\nThis parameter prevents that by setting a maximum number of signs that any single zone can contribute to your pool. Even if a zone has a hundred active signs, your client will only take this many from it before moving on to the next zone.\r\n\r\nThe practical effect is geographic variety in your sign pool: results come from multiple areas rather than being dominated by one hotspot. This matters most in areas where multiple zones of varying population density sit close together.\r\n\r\nThis value must always be lower than or equal to Sign Pool (Total). Setting it higher than the total pool is meaningless — the total cap is the absolute ceiling on how many signs you can hold, regardless of how many any single zone could supply.",
		AdvancedDetails: "PARAMDEF SortID: 106 — 召喚サイン所持可能数上限(セル) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x24  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 10\r\nValidation: 1–99\r\nCross-field constraint: must be ≤ ReloadSignTotalCount (0x20). ValidateNetworkParams enforces this.",
	},
	{
		Key: "singGetMax", View: ViewSign,
		Label: "Sign buffer cap", Internal: "SingGetMax", Type: "int32",
		Advanced: false, Min: 10, Max: 96, UnlockMin: 1, UnlockMax: 128,
		Warning: "Must be ≥ Sign Pool (Total). Also, the game server may enforce its own independent cap — client values above that server limit are silently ignored.",
		ShortDef: "Maximum signs the server returns in a single response. Acts as a hard ceiling on Sign Pool (Total) — if smaller than the total pool, the pool can never be fully filled regardless of activity.\r\nRaise → server can return larger batches; required before increasing the total pool beyond the current cap.\r\nLower → server responses truncated; Sign Pool (Total) is effectively capped at this value even if set higher.",
		LongDef: "When your game asks the server for signs, the server decides how many to include in its response. This parameter tells the server the maximum number you are willing to receive. No matter how large your local sign pool is set, you cannot receive more signs per refresh than this number allows.\r\n\r\nThis creates a dependency: Sign Pool (Total) is how many signs your game stores locally, but Sign Buffer Cap is the most you can ever receive in one server response to fill that pool. If you raise Sign Pool (Total) to 64 but leave this at the default of 32, the server will still only ever send 32 signs — leaving your 64-slot pool permanently half empty.\r\n\r\nThe correct order when increasing sign visibility is: raise this cap first, then raise the total pool, then adjust the per-cell cap proportionally.\r\n\r\nBe aware that the game's own servers may also enforce an independent ceiling that no client-side setting can change. If you set this very high and see no improvement in the number of signs visible, you may have reached that server-enforced limit.",
		AdvancedDetails: "PARAMDEF SortID: 122 — サイン取得上限 (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x60  |  Type: int32\r\nVanilla value: 32\r\nValidation: 1–128\r\nCross-field constraint: must be ≥ ReloadSignTotalCount (0x20). ValidateNetworkParams enforces this.\r\nNote: the game server may impose its own independent cap. Client-side values above that server cap are silently clamped server-side.",
	},
	{
		Key: "updateSignIntervalTime", View: ViewSign,
		Label: "Sign upload interval", Internal: "UpdateSignIntervalTime", Type: "float32",
		Advanced: false, Min: 5, Max: 120, UnlockMin: 1, UnlockMax: 999,
		ShortDef: "Re-registration heartbeat for your own placed sign — how often the client confirms sign validity to the server to prevent silent expiry.\r\nRaise → less frequent heartbeats; sign risks expiring silently during extended waits.\r\nLower → more frequent confirmation pings; substantially reduces the chance of your sign disappearing from others' pools.",
		LongDef: "When you place a summon sign, you are telling the server that you want to be summoned from that location. But signs on the server expire after a period of inactivity — if the server does not hear from your game confirming that you are still there and still waiting, it eventually removes your sign from the lists it provides to other players.\r\n\r\nThis parameter controls how often your game automatically sends that confirmation — a regular message that keeps your sign marked as active. Think of it as a heartbeat for your placed sign.\r\n\r\nAt the default of 30 seconds, your game confirms twice per minute. This is sufficient for short waits. But if you sit near a fog gate for ten or fifteen minutes waiting to be summoned, there is a meaningful chance that a network hiccup causes one of those confirmation messages to fail to reach the server, and your sign silently disappears from everyone else's view with no notification to you.\r\n\r\nReducing this to 10–15 seconds means your game sends confirmations more frequently, making it much harder for a single dropped message to cause your sign to expire. Raising it beyond 30 seconds saves a small amount of server traffic but meaningfully increases the risk of silent sign loss during long waits.",
		AdvancedDetails: "PARAMDEF SortID: 107 — 召喚サイン更新待機時間[秒] (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x28  |  Type: float32\r\nVanilla value: 30 s\r\nValidation: 1–1000 s\r\nThis governs re-registration of the player's own sign specifically. Distinct from SignDownloadSpan (0x64) and SignUpdateSpan (0x68), which handle bulk background data synchronization.",
	},
	{
		Key: "signDownloadSpan", View: ViewSign,
		Label: "Sign download span", Internal: "SignDownloadSpan", Type: "float32",
		Advanced: false, Min: 5, Max: 120, UnlockMin: 1, UnlockMax: 999,
		ShortDef: "Trickle update interval — minimum gap between incremental background downloads that propagate individual sign changes between full cache refreshes.\r\nRaise → sign changes accumulate until the next full refresh; pool feels more static between cycles.\r\nLower → individual changes propagate faster; smoother, more continuous updates between full refreshes.",
		LongDef: "The game uses two separate mechanisms to keep your sign pool up to date. The first is the full refresh controlled by Sign Refresh Interval: every so often, your game completely replaces its local sign list with a fresh download from the server.\r\n\r\nThe second mechanism — the one this parameter controls — is a lighter background update that runs between those full refreshes. Rather than waiting for the next complete reset, your game periodically fetches just the changes: signs that newly appeared and signs that were removed, without rebuilding the entire list from scratch.\r\n\r\nThink of the full refresh as replacing a newspaper with a new edition, and the download span as getting individual article corrections between editions.\r\n\r\nLowering this value makes those between-refresh corrections arrive more frequently, so the sign pool feels more continuously alive rather than staying static for long periods and then jumping all at once during a full refresh. Raising it makes updates more intermittent — you see the pool remain unchanged for longer and then suddenly shift when the next full refresh lands.",
		AdvancedDetails: "PARAMDEF SortID: 123 — サインダウンロードスパン (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x64  |  Type: float32\r\nVanilla value: 30 s\r\nValidation: 1–1000 s\r\nWorks in conjunction with ReloadSignIntervalTime2 (full refresh, 0x1C) and SignUpdateSpan (upload direction, 0x68).",
	},
	{
		Key: "signUpdateSpan", View: ViewSign,
		Label: "Sign upload span", Internal: "SignUpdateSpan", Type: "float32",
		Advanced: false, Min: 5, Max: 120, UnlockMin: 1, UnlockMax: 999,
		ShortDef: "Outgoing sync interval — minimum gap between background uploads of local sign state to the server. Upload counterpart to Sign Download Span.\r\nRaise → your client reports local sign activity less often; the server's view of your area grows stale.\r\nLower → more frequent outgoing updates; the server stays better informed, improving sign accuracy for nearby players.",
		LongDef: "The sign sync system works in two directions. The previous parameters cover how your game downloads sign information from the server. This one covers the other direction: how often your game uploads information about your local sign activity back to the server.\r\n\r\nThis upload matters because the server's database needs to stay accurate. If signs are being placed, removed, or interacted with in your area, the server needs to know about it to give accurate information to other players who are searching nearby.\r\n\r\nThe practical effect of this parameter is mostly indirect — it does not change what you see on screen, but it affects what other players see when they search for signs in your area. Lowering it means your game reports outgoing activity more often, keeping the server's picture of your surroundings more current, which improves the sign experience for nearby players.\r\n\r\nRaising it significantly can create a visible lag between local events and when other players see those events reflected in their own sign pools.",
		AdvancedDetails: "PARAMDEF SortID: 124 — サインアップロードスパン (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x68  |  Type: float32\r\nVanilla value: 60 s\r\nValidation: 1–1000 s\r\nUpload counterpart to SignDownloadSpan (0x64). Distinct from UpdateSignIntervalTime (0x28), which handles re-registration of the player's own placed sign specifically.",
	},
	// --- Advanced params (not edited by SaveForge) ---
	{
		Key: "summonTimeoutTime", View: ViewSign,
		Label: "Summon timeout", Internal: "SummonTimeoutTime", Type: "float32",
		Advanced: true, Min: 10, Max: 600, UnlockMin: 1, UnlockMax: 999,
		ShortDef: "Global handshake deadline for co-op summons. Times out the full phantom-loading process from sign interaction to in-world appearance. On expiry the sign silently reappears; both players see a failed loading screen.\r\nRaise → marginal long-distance connections get more time; stuck loading screens run longer on failure.\r\nLower → failed summons clear faster; close-to-expiry connections may be cut prematurely.",
		LongDef: "When a host interacts with your summon sign, both your game and theirs begin a connection process. Your character needs to be loaded into their world, your equipment synchronised, and a stable link established between the two games. This normally takes between 5 and 20 seconds when everything works correctly.\r\n\r\nSometimes the process stalls. Poor network conditions, firewall settings blocking the direct connection, or the host moving to a different area can all prevent it from completing. When that happens, both players see a spinning loading indicator that simply stays there — you cannot interact or do anything. This parameter defines the maximum time that loading process is allowed to run before the game abandons it.\r\n\r\nWhen this timer expires, your sign silently reappears on the ground and both players return to their game with no explanation of what happened.\r\n\r\nThe vanilla value is 45 seconds, which is already generous — most successful summons complete well under 20 seconds. Lowering it means failed attempts resolve faster, reducing time spent watching a stuck loading screen. The trade-off is that slow but potentially successful connections — most common when matching with players in distant countries — may be cut before they finish.\r\n\r\nNote: this setting is shared across all summoning types in the game, not just signs placed with the Furlcalling Finger Remedy.",
		AdvancedDetails: "PARAMDEF SortID: 2 — 召喚タイムアウト時間[秒] (NET_COMMON_PARAM — shared across all summoning types, not sign-specific)\r\nMemory offset: 0x08  |  Type: float32\r\nVanilla value: 45 s (confirmed from actual PS4 save file)\r\nValidation: 10–600 s casual, 1–999 s advanced",
	},
	{
		Key: "reloadSignIntervalTime1", View: ViewSign,
		Label: "Inactive refresh interval", Internal: "ReloadSignIntervalTime1", Type: "float32",
		Advanced: true, Min: 0, Max: 120, UnlockMin: 0, UnlockMax: 999,
		Confidence: CommunityInferred,
		ShortDef: "Separate refresh rate for when the player is not in an active sign context. At 0 (shipped default) the system is disabled and the standard refresh interval applies everywhere. Non-zero enables a two-speed mode.\r\nSet to 0 → single rate in all contexts; vanilla behaviour.\r\nSet above 0 → slower background polling during exploration; reduces traffic without slowing the active sign experience.",
		LongDef: "Normally, the Sign Refresh Interval you set applies all the time — whether you are standing at a fog gate actively waiting for a summon, or sprinting through an empty dungeon far from any signs.\r\n\r\nThis parameter can optionally create a second, slower refresh rate that takes over when you are not in an active sign context — for example, when you are in combat, exploring, or in areas with no sign activity nearby.\r\n\r\nThe game ships this field at 0, which means the system is disabled: the active rate from Sign Refresh Interval applies everywhere regardless of context. This is the simplest and most predictable behaviour, and for most players it is the right choice.\r\n\r\nSetting a non-zero value here enables the two-speed system. For example: Sign Refresh Interval at 10 seconds for active sign areas, this field at 60 seconds for everywhere else. The game switches between the two rates based on context, reducing server traffic during exploration without making the sign pool feel slow near fog gates.\r\n\r\nThe exact conditions the game uses to determine active versus inactive sign context are community-inferred — the precise moment the game switches between rates is not fully documented.",
		AdvancedDetails: "PARAMDEF SortID: 102 — 召喚サイン再取得待機時間(非活性)[秒] (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x18  |  Type: float32\r\nActual shipped regulation value: 0 (PARAMDEF lists default = 1 but the regulation ships 0)\r\nValidation: 0–1000 s  |  0 is explicitly valid — means 'use active timer (reloadSignIntervalTime2)'\r\nCompanion to ReloadSignIntervalTime2 (active timer, offset 0x1C).",
	},
	{
		Key: "signCellRangeH", View: ViewSign,
		Label: "Cell range (horizontal)", Internal: "SignCellRangeH", Type: "int32",
		Advanced: true, Min: 1, Max: 5, UnlockMin: 1, UnlockMax: 10,
		Confidence: CommunityInferred,
		Warning:    "Raising cell range without proportionally increasing Sign Pool (Total) and Sign Buffer Cap causes extra results to be silently truncated.",
		ShortDef: "Horizontal radius of the spatial search volume in matchmaking cells. Value of 1 = current cell only; each increment expands outward by one ring, multiplying the searched area.\r\nRaise → exponentially more cells searched; more signs from a wider horizontal area.\r\nLower → narrower horizontal search; players spread across adjacent cells may be missed.",
		LongDef: "The game divides the world into a three-dimensional grid of invisible zones called cells for multiplayer matchmaking. When your game fetches summon signs, it searches for signs within a volume of cells centred on your position.\r\n\r\nThis parameter controls how far that search extends horizontally. At the default value of 1, the search covers only the single cell you are standing in. Raising it to 2 expands the search to include one ring of surrounding cells — a 3×3 grid of 9 cells. Raising it to 3 covers a 5×5 grid of 25 cells. Each step outward multiplies the searched area significantly.\r\n\r\nThe horizontal range matters most in wide-open areas like Limgrave, Liurnia, or the Mountaintops of the Giants, where players naturally spread out across many cells. In tight dungeon corridors the benefit is smaller since adjacent cells contain fewer players anyway.\r\n\r\nIf you raise this value without also raising Sign Pool (Total) and Sign Buffer Cap, the additional cells are searched but the extra signs they contain are simply cut off to fit the existing pool size. You must increase the cache capacity alongside the search volume for the change to have any visible effect on how many signs you see.",
		AdvancedDetails: "PARAMDEF SortID: 113 — 召喚サイン取得セル範囲(水平) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x3C  |  Type: int32 (stored as u32 — 4 bytes despite PARAMDEF note 'actually u8' for value range)\r\nVanilla value: 1\r\nValidation: 1–5 casual, 1–10 advanced\r\nLayout verification: 3 u32 fields × 4 B (0x3C/0x40/0x44) + 6 f32 keyword-scale fields × 4 B (0x48–0x5F) = 36 B → SingGetMax at 0x60 ✓",
	},
	{
		Key: "signCellRangeUp", View: ViewSign,
		Label: "Cell range (upward)", Internal: "SignCellRangeUp", Type: "int32",
		Advanced: true, Min: 1, Max: 5, UnlockMin: 1, UnlockMax: 10,
		Confidence: CommunityInferred,
		Warning:    "Raising cell range without proportionally increasing Sign Pool (Total) and Sign Buffer Cap causes extra results to be silently truncated.",
		ShortDef: "Upward component of the 3D search volume — how many cell layers above the player are included when fetching signs.\r\nRaise → signs from elevated positions and upper floors become visible.\r\nLower → only the current vertical cell is searched; players on higher floors are excluded.",
		LongDef: "Elden Ring has significant vertical complexity — many dungeons, towers, and buildings have multiple floors, and the underground regions of the world sit directly below the surface. The matchmaking cell grid extends vertically as well as horizontally.\r\n\r\nThis parameter controls how many cell layers above your current position are searched when fetching signs. At the default of 1, only your current vertical level is covered. A host standing at the base of Raya Lucaria Academy cannot see signs from a phantom standing on the upper floors, because they occupy different vertical cells.\r\n\r\nRaising this value bridges those vertical gaps. Setting it to 2 means your search reaches one cell layer upward, connecting floors that would otherwise be separated in the sign pool.\r\n\r\nThis is most impactful in: multi-story legacy dungeons (Stormveil, Raya Lucaria, Elphael Brace of the Haligtree), areas with significant elevation variation across a short horizontal distance, and transition zones between the surface world and underground areas.\r\n\r\nAs with horizontal range, raising this without also increasing Sign Pool (Total) and Sign Buffer Cap produces no visible improvement — additional cells are searched but results are silently truncated to fit the existing cache.",
		AdvancedDetails: "PARAMDEF SortID: 114 — 召喚サイン取得セル範囲(上方向) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x40  |  Type: int32 (stored as u32 — same 4-byte storage note as SignCellRangeH)\r\nVanilla value: 1\r\nValidation: 1–5 casual, 1–10 advanced\r\nWorks with SignCellRangeH (0x3C) and SignCellRangeDown (0x44) to define the full 3D search volume.",
	},
	{
		Key: "signCellRangeDown", View: ViewSign,
		Label: "Cell range (downward)", Internal: "SignCellRangeDown", Type: "int32",
		Advanced: true, Min: 1, Max: 5, UnlockMin: 1, UnlockMax: 10,
		Confidence: CommunityInferred,
		Warning:    "Raising cell range without proportionally increasing Sign Pool (Total) and Sign Buffer Cap causes extra results to be silently truncated.",
		ShortDef: "Downward component of the 3D search volume — how many cell layers below the player are included when fetching signs.\r\nRaise → signs from lower floors and underground areas become visible to players above.\r\nLower → only the current vertical cell is searched; players in underground areas beneath you are excluded.",
		LongDef: "The downward counterpart to Cell Range (Upward). While that parameter lets you see signs from players above you, this one opens visibility to players below — and symmetrically lets hosts above see signs from you when you are in a lower area.\r\n\r\nElden Ring connects its surface and underground worlds through vertical layers: parts of Limgrave sit above Siofra River, areas of Leyndell connect to the underground city, and cave systems run beneath outdoor zones. A host standing on the surface normally cannot see signs from phantoms exploring directly below them in an underground region, because they occupy different vertical cells.\r\n\r\nRaising the downward range opens up those cross-level connections. A surface host with a downward range of 2 can see signs from phantoms one vertical cell below — potentially in the underground region directly beneath the surface area.\r\n\r\nFor most situations, setting upward and downward range to matching values makes sense, since you generally want symmetric vertical coverage. If your session is entirely underground or entirely on the surface, you can tilt the balance toward the relevant direction.\r\n\r\nAs with all cell range parameters, the pool size must scale proportionally — raise Sign Pool (Total) and Sign Buffer Cap alongside range to avoid silent result truncation.",
		AdvancedDetails: "PARAMDEF SortID: 115 — 召喚サイン取得セル範囲(下方向) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x44  |  Type: int32 (stored as u32 — same 4-byte storage note as SignCellRangeH)\r\nVanilla value: 1\r\nValidation: 1–5 casual, 1–10 advanced\r\nAll three cell-range parameters (0x3C/0x40/0x44) define a rectangular 3D search volume. Adjust together when increasing overall spatial coverage.",
	},
}
