package params

// ---------------------------------------------------------------------------
// Hunter params — NET_VISIT_PARAM + NET_EXTRA_PARAM
// 8 params: 7 basic (matching SaveForge), 1 advanced (not edited by SaveForge).
// Basic sorted: cooldown, list size, summon cap, search timing pair, area rates pair.
// ---------------------------------------------------------------------------

var hunterParams = []ParamMeta{
	{
		Key: "reloadVisitListCoolTime", View: ViewHunter,
		Label: "Visit list cooldown", Internal: "ReloadVisitListCoolTime", Type: "float32",
		Advanced: false, Min: 3, Max: 60, UnlockMin: 1, UnlockMax: 999,
		ShortDef: "Polling interval for the Blue Cipher Ring search loop — how long the client waits between cycles checking the server for an available invaded world.\r\nRaise → less frequent checks; the game responds to new invasions more slowly.\r\nLower → more frequent queries; dispatch happens closer to the moment an invasion becomes available.",
		LongDef: "When you equip the Blue Cipher Ring, your game runs a background process that repeatedly checks a server for invaded worlds that need a Hunter. It does not watch continuously — it checks, waits a set amount of time, then checks again in an ongoing loop.\r\n\r\nThis parameter controls how long that wait is between checks.\r\n\r\nAt the default of 20 seconds, your game asks the server roughly three times per minute whether an invaded world is available for you. If an invasion begins in between two of those checks, your game will not see it until the next check fires. In active PvP periods where invasions start and end quickly, missing that window means you never get dispatched for that particular event at all.\r\n\r\nReducing this to 5–8 seconds means your game checks much more frequently, dramatically narrowing the gap between when an invasion becomes available and when you are dispatched to it. The practical benefit diminishes below about 3 seconds because the server has its own minimum processing time for each request regardless of how often you ask.\r\n\r\nRaising it beyond the default makes you respond to invasions more slowly with no benefit in return.",
		AdvancedDetails: "PARAMDEF SortID: 600 — 指輪検索間隔[秒] (NET_VISIT_PARAM)\r\nMemory offset: 0x180  |  Type: float32\r\nVanilla value: 20 s\r\nValidation: 1–1000 s\r\nGoverns search loop for all Blue Cipher Ring variants. Distinct from Co-op Search Min/Max (0x190/0x194), which govern a separate randomized interval mechanism.",
	},
	{
		Key: "maxVisitListCount", View: ViewHunter,
		Label: "Visit list size", Internal: "MaxVisitListCount", Type: "int32",
		Advanced: false, Min: 1, Max: 20, UnlockMin: 1, UnlockMax: 50,
		ShortDef: "Candidates per Hunter search cycle — direct analog to Target List Size for invaders. The client tries each entry in sequence; a larger list reduces wasted cycles when many worlds exist but are incompatible.\r\nRaise → more worlds to attempt per cycle; fewer completely wasted cooldowns.\r\nLower → smaller batch; the cycle wastes more often on incompatible or unreachable entries.",
		LongDef: "Each time the Blue Cipher Ring search cycle fires, your game receives a list of invaded worlds it could potentially enter as a Hunter. It then tries each one in sequence — checking that your character's level is compatible, that there is room for another phantom, and that a connection can be established.\r\n\r\nThis parameter controls how long that list is. At the default of 5, your game receives five options per cycle. If all five fail — the invader was already defeated, the host moved to a safe area, level ranges do not match, or connections could not be established — the cycle ends without dispatching you anywhere, and the cooldown begins again.\r\n\r\nRaising this value gives more options before a cycle is completely wasted. In active PvP sessions with many simultaneous invasions, the server may have many invaded worlds to offer, but a significant portion may not be compatible with your specific character's level or weapon upgrade. A longer list gives you more chances of finding a compatible match within each cycle rather than waiting through another full cooldown.\r\n\r\nThis parameter works exactly the same way as Target List Size in the invasion system — both control how many candidates the game works through per search round.",
		AdvancedDetails: "PARAMDEF SortID: 603 — 指輪検索先取得数 (NET_VISIT_PARAM)\r\nMemory offset: 0x18C  |  Type: int32 (stored as u32)\r\nVanilla value: 5\r\nValidation: 1–50 (all modes)\r\nDirect analog to MaxBreakInTargetListCount (0x70) for the Hunter role.",
	},
	{
		Key: "maxCoopBlueSummonCount", View: ViewHunter,
		Label: "Co-op blue summon cap", Internal: "MaxCoopBlueSummonCount", Type: "int32",
		Advanced: false, Min: 1, Max: 5, UnlockMin: 1, UnlockMax: 10,
		Warning: "The game server enforces its own session cap that overrides this value in standard online play. Raising above 2 has no observable effect.",
		ShortDef: "Client-side ceiling on simultaneous Blue Phantoms. Has no observable effect in standard online play — the game server enforces its own cap that overrides this value.\r\nRaise → no effect in standard play; server cap still limits actual joins.\r\nLower → artificially restricts Blue Phantom presence below the server's intended limit.",
		LongDef: "In an online session, there is a limit to how many Blue Phantoms — Hunters summoned through the Blue Cipher Ring — can be present in a world at the same time. This limit is checked in two places: by your game client locally, and by FromSoftware's servers centrally.\r\n\r\nThis parameter controls only the client-side check — what your own game treats as the maximum. The server independently enforces its own separate cap, and that server cap is the one that actually determines how many Blue Phantoms can appear in practice during standard online play.\r\n\r\nRaising this above 2 simply removes the client's local check. Since the server still enforces its own limit, the result in normal online play is identical — you cannot increase the actual number of Blue Phantoms in a session by changing this value alone. Doing so would require also changing what the server enforces, which is not possible through save file editing.\r\n\r\nLowering it below 2 artificially restricts the game below the server's intended behaviour and reduces the effectiveness of co-op without any benefit. The only situation where this setting has any visible effect is in custom server environments that have independently raised their own session limits.",
		AdvancedDetails: "PARAMDEF SortID: 601 — 救援青霊出現数上限 (NET_VISIT_PARAM)\r\nMemory offset: 0x184  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 2\r\nValidation: 1–10 (all modes)\r\nThe server enforces a separate, independent cap. Client values above that server cap are silently no-ops in standard online play.",
	},
	{
		Key: "reloadSearchCoopBlueMin", View: ViewHunter,
		Label: "Co-op search min", Internal: "ReloadSearchCoopBlueMin", Type: "float32",
		Advanced: false, Min: 3, Max: 120, UnlockMin: 1, UnlockMax: 999,
		Warning: "Must not exceed Co-op Search Max. If min > max the random interval selection is undefined.",
		ShortDef: "Lower bound of the randomised inter-cycle wait. Actual wait is drawn uniformly from [min, max] each cycle; since average = (min + max) ÷ 2, reducing only the minimum has limited impact — reducing the maximum is far more effective.\r\nRaise → extends even the shortest possible waits.\r\nLower → reduces the floor; modest gain unless the maximum is also reduced.",
		LongDef: "Between each Hunter search cycle, your game waits a random amount of time before checking for available invaded worlds again. That wait is not a fixed duration — it is a random value chosen somewhere between a minimum and a maximum. This parameter sets the minimum.\r\n\r\nThe randomness exists for a practical reason: if every player with the Blue Cipher Ring equipped checked the server at exactly the same instant, the resulting traffic spike could cause performance problems for everyone. The random spread distributes server load by having different players check at slightly different times.\r\n\r\nThe minimum determines the shortest wait that can ever occur. However, because the actual wait is chosen randomly anywhere between the minimum and the maximum, the average wait is simply halfway between them. At the default values — 30 seconds minimum, 180 seconds maximum — the average wait between cycles is 105 seconds.\r\n\r\nReducing only the minimum from 30 to 3 seconds moves the average to about 91 seconds. That is an improvement, but a modest one. The maximum has a far larger effect on the average, which is why reducing both values together produces the most noticeable improvement in how quickly you get dispatched.",
		AdvancedDetails: "PARAMDEF SortID: 604 — 救援青霊リロード時間 最小[sec] (NET_VISIT_PARAM)\r\nMemory offset: 0x190  |  Type: float32\r\nVanilla value: 30 s\r\nValidation: 1–999 s\r\nCross-field constraint: must be ≤ ReloadSearchCoopBlueMax (0x194). The actual per-cycle wait is drawn from Uniform(min, max). ValidateNetworkParams enforces the min ≤ max invariant.",
	},
	{
		Key: "reloadSearchCoopBlueMax", View: ViewHunter,
		Label: "Co-op search max", Internal: "ReloadSearchCoopBlueMax", Type: "float32",
		Advanced: false, Min: 10, Max: 300, UnlockMin: 1, UnlockMax: 999,
		Warning: "Must not be less than Co-op Search Min. ValidateNetworkParams enforces this constraint.",
		ShortDef: "Upper bound of the randomised inter-cycle wait — the single most impactful parameter for Hunter dispatch frequency. Since average = (min + max) ÷ 2, halving the maximum roughly halves the average wait.\r\nRaise → longer worst-case waits; Hunter dispatch becomes passive and unpredictable.\r\nLower → most effective single lever for faster dispatch; eliminates long-wait outliers.",
		LongDef: "This is the companion to Co-op Search Min: it sets the upper end of the random wait between Hunter search cycles. The game picks a random duration somewhere between the minimum and this maximum before each new cycle begins.\r\n\r\nBecause the wait is uniformly random between the two values, the average comes out to exactly halfway: (minimum + maximum) ÷ 2. The maximum therefore has the greatest influence on how quickly you get dispatched on average.\r\n\r\nAt the game's default values — 30 seconds minimum, 180 seconds maximum — the average wait between cycles is 105 seconds. The worst-case wait is 180 seconds, meaning you could sit with the Blue Cipher Ring equipped for three minutes without being dispatched, simply due to bad random luck. Reducing the maximum to 45 seconds while leaving the minimum at 30 drops the average to about 37 seconds.\r\n\r\nFor the fastest dispatch, reduce both values together to a narrow range. A minimum of 3 seconds and a maximum of 15 seconds gives an average wait of 9 seconds — approximately 12 times faster than the default — while keeping the randomisation that prevents every Hunter from hitting the server at the same moment.\r\n\r\nThis must always be set at or above the minimum. If the maximum falls below the minimum, the random selection becomes undefined.",
		AdvancedDetails: "PARAMDEF SortID: 605 — 救援青霊リロード時間 最大[sec] (NET_VISIT_PARAM)\r\nMemory offset: 0x194  |  Type: float32\r\nVanilla value: 180 s\r\nValidation: 1–999 s\r\nCross-field constraint: must be ≥ ReloadSearchCoopBlueMin (0x190). ValidateNetworkParams enforces this invariant.",
	},
	{
		Key: "allAreaSearchRateCoopBlue", View: ViewHunter,
		Label: "Co-op all-area rate (%)", Internal: "AllAreaSearchRateCoopBlue", Type: "int32",
		Advanced: false, Min: 0, Max: 100, UnlockMin: 0, UnlockMax: 100,
		Confidence: CommunityInferred,
		ShortDef: "Probability (0–100) that a given search cycle queries the entire map rather than only the player's local region. Controls geographic scope for the co-op assist trigger.\r\nRaise → more searches go global; better dispatch rate when local invasion activity is sparse.\r\nLower → local-focused searches; lower connection latency but fewer dispatches when your area is quiet.",
		LongDef: "When the game searches for an invaded world to send you to, it can either search close to where your character currently is on the map, or it can search the entire world regardless of location. Local searches tend to connect you with players who have better network proximity to you, since players in the same region typically share internet infrastructure. However, if no invasions are happening locally, a local-only search will consistently come up empty.\r\n\r\nThis parameter controls how often a search covers the whole map instead of staying local. Each cycle the game effectively rolls a random number: if the result falls below this percentage, the search goes global; otherwise it stays local.\r\n\r\nAt the default of 30%, roughly one in three searches covers the entire world. During quiet periods when few invasions are happening in your local region, those two out of three local searches will find nothing. Raising this value toward 60–80% means most of your searches cover the full map, dramatically improving dispatch rates when nearby activity is low.\r\n\r\nThe trade-off: a global match may connect you with a player in a distant country, which can mean noticeably higher latency. Whether that trade-off is worth it depends on whether you prioritise being dispatched frequently or prioritise connection quality when you are dispatched.",
		AdvancedDetails: "PARAMDEF SortID: 730 — 全域検索率：救援青霊 (NET_EXTRA_PARAM)\r\nMemory offset: 0x1D8  |  Type: u8 (1 byte), stored as int32 in the struct\r\nVanilla value: 30\r\nValidation: 0–100 (strict percentage)\r\nThe three all-area rate bytes are stored consecutively: 0x1D8 (CoopBlue), 0x1D9 (VsBlue), 0x1DA (BellGuard).",
	},
	{
		Key: "allAreaSearchRateVsBlue", View: ViewHunter,
		Label: "Hunter all-area rate (%)", Internal: "AllAreaSearchRateVsBlue", Type: "int32",
		Advanced: false, Min: 0, Max: 100, UnlockMin: 0, UnlockMax: 100,
		Confidence: CommunityInferred,
		ShortDef: "All-area rate for the 'retribution' Blue Cipher Ring trigger — a second activation pathway distinct from the co-op assist search. Identical mechanic to Co-op All-Area Rate but for a separate trigger type.\r\nRaise → more global searches for this trigger type.\r\nLower → geographically constrained searches for this trigger.",
		LongDef: "The Blue Cipher Ring can be triggered through more than one pathway. The main one — governed by Co-op All-Area Rate — activates when a player using the White Cipher Ring calls for help. This parameter covers a second trigger type, labelled 'retribution' in the game's internal data.\r\n\r\nIn Dark Souls 3, this distinction was clearly visible to players: the Blue Sentinel covenant responded specifically to active invasion events, while the Way of Blue responded to deliberate co-op calls. These were genuinely separate trigger pathways with different search priorities. Elden Ring's data preserves that same internal distinction.\r\n\r\nIn Elden Ring's player-facing design, the separation is less explicit. The game does not explain to players exactly when the 'retribution' trigger fires versus the co-op assist trigger, and community testing on the practical difference between the two in Elden Ring has not produced definitive results.\r\n\r\nFor practical purposes, keeping this value in line with Co-op All-Area Rate is a reasonable default. Setting them to different values is possible if you want to tune the two trigger types separately, but the exact behavioural difference is not fully established.",
		AdvancedDetails: "PARAMDEF SortID: 730 — 全域検索率：報復青霊 (NET_EXTRA_PARAM)\r\nMemory offset: 0x1D9  |  Type: u8 (1 byte), stored as int32 in struct\r\nVanilla value: 30\r\nValidation: 0–100\r\nThe '報復青霊' (retribution/revenge blue spirit) designation likely originates from DS3's Blue Sentinels covenant. In ER the trigger conditions may differ from earlier titles.",
	},
	// --- Advanced params (not edited by SaveForge) ---
	{
		Key: "allAreaSearchRateBellGuard", View: ViewHunter,
		Label: "Bell-guard all-area rate (%)", Internal: "AllAreaSearchRateBellGuard", Type: "int32",
		Advanced: true, Min: 0, Max: 100, UnlockMin: 0, UnlockMax: 100,
		Confidence: Unconfirmed,
		Warning:    "In-game trigger conditions in Elden Ring are unconfirmed. This field is a legacy remnant from Dark Souls 2's Bell Keeper covenant and may be vestigial.",
		ShortDef: "All-area rate for the 'bell guardian' phantom type — a third trigger variant from DS2's Bell Keeper system. No confirmed player-facing trigger for this type exists in Elden Ring; the field may be vestigial.\r\nRaise → increased global search rate if this trigger is active in ER.\r\nLower → geographically constrained search; equally uncertain in practice.",
		LongDef: "In Dark Souls 2, certain areas of the game world contained bell towers that players could choose to trespass in. A PvP covenant called the Bell Keepers automatically summoned its members to defend those towers against intruders — an early automated, location-based invasion system tied to specific points on the map rather than general PvP activity flags.\r\n\r\nThis parameter is a direct descendant of that system. The game's internal data includes a 'bell guardian' phantom type stored immediately after the co-op and retribution all-area rates. Its name in Japanese — 鐘守灰霊 — translates to 'bell guardian spirit' and is the same internal designation used in Dark Souls 2.\r\n\r\nElden Ring does not appear to have a bell guardian system in its player-facing content. There are no bell towers with designated defenders, no Bell Keeper-equivalent covenant, and no item described as triggering this phantom type. The parameter exists in the regulation data and holds a non-zero live value, but whether it does anything in Elden Ring is not confirmed by community testing.\r\n\r\nThis parameter is exposed here for completeness. Adjusting it alongside the other all-area rates is technically harmless, but any practical effect it may have in Elden Ring is unknown.",
		AdvancedDetails: "PARAMDEF SortID: 730 — 全域検索率：鐘守灰霊 (NET_EXTRA_PARAM)\r\nMemory offset: 0x1DA  |  Type: u8 (1 byte), stored as int32 in struct\r\nVanilla value: 30\r\nValidation: 0–100\r\nThe '鐘守灰霊' (bell guardian spirit) name connects to DS2's Bell Keeper covenant.\r\nIn-game trigger conditions in ER: unconfirmed by community testing as of this writing.",
	},
}
