package app

import "math"


// ---------------------------------------------------------------------------
// Taunter's Tongue params — VISITOR
// 3 params, all basic. Advanced mode expands slider limits only.
// ---------------------------------------------------------------------------

var tongueParams = []ParamMeta{
	{
		Key: "visitorListMax", View: ViewTongue,
		Label: "Visitor list size", Internal: "VisitorListMax", Type: "int32",
		Advanced: false, Min: 1, Max: 30, AdvancedMin: 1, AdvancedMax: float64(math.MaxInt32),
		ShortDef: "How many potential invaders the game fetches per search cycle while Taunter's Tongue is active. A larger list gives the matchmaking system more candidates to try per cycle, reducing the average wait between invasions.\r\nRaising it → more invader candidates per request; faster cycling through incompatible options, especially useful when many invaders are online but most are in different level ranges.\r\nLowering it → fewer candidates per request; the game may exhaust its small list quickly and have to wait for the next cycle.",
		LongDef: "When Taunter's Tongue is active, your world is advertised to invasion-seeking players as a valid target even without a cooperator present. Simultaneously, your game runs its own search loop: periodically fetching a list of invasion-ready players and initiating the connection handshake with them.\r\n\r\nThis parameter sets how many invaders are in each fetched list. With the vanilla value of 10, your client has 10 candidates to attempt per cycle. If all 10 fail to connect — wrong level range, already invading someone else, disconnected — your client waits the Visitor Download Span interval and fetches a new list.\r\n\r\nRaising this value works exactly like raising Target List Size for invaders: more candidates per request means fewer completely-wasted cycles. In sessions where many invaders are online but most are outside your matchmaking window, a larger list gives you a better statistical chance of finding a compatible match in each batch without waiting for the next download.\r\n\r\nThe difference from the invader side: rather than reaching out to host worlds, you are pulling invaders toward your world. The direction of the 'invitation' is reversed but the candidate-list mechanics are identical.",
		AdvancedDetails: "PARAMDEF SortID: 1500 — 訪問対象者リスト取得最大値 (VISITOR param group)\r\nMemory offset: 0x240  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 10\r\nValidation: 1–100 (all modes)\r\nThe VISITOR group (0x240–0x248) is structurally independent from NET_VISIT_PARAM (Hunter params at 0x180–0x194) despite both relating to multiplayer player traffic.",
	},
	{
		Key: "visitorTimeOutTime", View: ViewTongue,
		Label: "Visitor timeout", Internal: "VisitorTimeOutTime", Type: "float32",
		Advanced: false, Min: 5, Max: 180, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "How long your game waits for an invader to complete their connection handshake before cancelling that slot and trying the next candidate on the list. Shorter values cycle through unresponsive invaders faster; longer values give slow connections more time to establish.\r\nRaising it → slow or distant invaders have more time to connect; fewer failed handshakes at the cost of longer waits when a connection truly can't establish.\r\nLowering it → unresponsive invaders are dropped quickly and the next candidate is tried immediately; faster cycling at the risk of cutting off legitimately slow but valid connections.",
		LongDef: "When your client selects an invader from its candidate list and initiates the session handshake, there is a window where both sides are negotiating the connection. This parameter is how long your client waits for that handshake to finish before giving up on that specific invader and moving to the next entry.\r\n\r\nIf you have used Taunter's Tongue and waited a long time with the invasion spinner active, it is likely because your client is cycling through a list of invaders who are not responding — each one consuming this full timeout before your client moves on. With the default 60 seconds and 10 candidates, a worst-case scenario where all 10 time out would mean 10 minutes of waiting.\r\n\r\nReducing this to 15–20 seconds keeps the total cycle time reasonable even when candidates are unresponsive. The tradeoff is that invaders in distant regions or on slower connections may need more than 15 seconds to establish the session — and those are exactly the invaders you'd be cutting off. A shorter timeout implicitly filters the player pool by connection responsiveness.\r\n\r\nRaising this significantly — to 120 seconds or more — dramatically extends worst-case wait times and is rarely useful in practice, since it means spending 2+ minutes waiting on each bad connection attempt.",
		AdvancedDetails: "PARAMDEF SortID: 1520 — 訪問待ちタイムアウト (VISITOR)\r\nMemory offset: 0x244  |  Type: float32\r\nVanilla value: 60 s\r\nValidation: 1–600 s\r\nDistinct from SummonTimeoutTime (0x08, NET_COMMON_PARAM), which governs the co-op summon handshake. This parameter applies specifically to the Taunter's Tongue visitor (invader) connection context.",
	},
	{
		Key: "visitorDownloadSpan", View: ViewTongue,
		Label: "Visitor download span", Internal: "VisitorDownloadSpan", Type: "float32",
		Advanced: false, Min: 5, Max: 180, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "How often your game downloads a fresh list of available invaders from the server while Taunter's Tongue is active. More frequent downloads mean recently-active invaders appear in your candidate pool sooner, reducing gaps between invasions during active PvP periods.\r\nRaising it → your invader candidate list grows stale between refreshes; you spend more time trying candidates who are no longer available.\r\nLowering it → fresh invaders appear in your pool sooner; less time wasted on outdated entries during high-activity PvP sessions.",
		LongDef: "Your client's invader candidate list has a limited lifespan — it was accurate when downloaded but grows stale as invaders log off, successfully invade other worlds, change areas, or move out of your matchmaking range. This parameter controls how often your client throws out its current list and downloads a fresh one from the server.\r\n\r\nWith the vanilla value of 60 seconds, your invader pool can be up to a minute out of date. During quiet periods this is not a problem — the same invaders are likely still available and looking for targets. During active PvP sessions where many invasions are starting and ending rapidly, however, a 60-second-old list is likely full of invaders who are already busy elsewhere, meaning your client wastes handshake attempts on candidates who will time out.\r\n\r\nReducing this span keeps your candidate list current, particularly during peak activity when the invader pool is turning over quickly. At 15–20 seconds, your list is rarely more than a fraction of a minute stale, and you are working with much more current data.\r\n\r\nRaising this value beyond 60 seconds creates longer windows of staleness, which can make Taunter's Tongue sessions feel sluggish even when invaders are available — you are simply trying to reach invaders who are already engaged elsewhere.",
		AdvancedDetails: "PARAMDEF SortID: 1530 — 訪問者リストダウンロード間隔[秒] (VISITOR)\r\nMemory offset: 0x248  |  Type: float32\r\nVanilla value: 60 s\r\nValidation: 1–600 s\r\nConceptual counterpart to SignDownloadSpan (0x64, NET_SUMMON_SIGN_PARAM) but operates in the Taunter's Tongue matchmaking path, not the co-op sign path.",
	},
}

