package app

import "math"

// ---------------------------------------------------------------------------
// Invader params — NET_BREAKIN_PARAM
// 4 params, all basic. Sorted: scope first (list size, area count), then timing (interval, timeout).
// ---------------------------------------------------------------------------

var invaderParams = []ParamMeta{
	{
		Key: "maxBreakInTargetListCount", View: ViewInvader,
		Label: "Target list size", Internal: "MaxBreakInTargetListCount", Type: "int32",
		Advanced: false, Min: 1, Max: 20, AdvancedMin: 1, AdvancedMax: float64(math.MaxInt32),
		ShortDef: "Controls how many candidate host worlds the game retrieves from the matchmaking server in a single search pass. A larger list means more options to evaluate before waiting for the next cycle, which directly reduces search time.\r\nRaising it → more candidates per request, higher chance of a quick match, especially in low-population areas.\r\nLowering it → fewer options per request; the game may exhaust the list quickly and restart the search interval unnecessarily.",
		LongDef: "When you activate an invasion item — Bloody Finger, Recusant Finger, or similar — your game client sends a request to FromSoftware's matchmaking server asking for a list of worlds you could potentially invade. The server checks its records for online hosts whose character level, weapon upgrade level, and region match your character's window, then hands back a list of results. This parameter sets the maximum length of that list.\r\n\r\nWith the game's default of 5, you get at most 5 candidate worlds per pass. Your client then tries to establish a connection with each one in turn. If all 5 fail — those hosts already have a full invasion, just died, changed areas, or have poor connectivity — the client waits the Search Interval and asks for a new list.\r\n\r\nRaising this value to 15 or 20 means you get more options per request. Since the server typically has far more eligible hosts logged than the default retrieves, a bigger list significantly increases the chance that at least one entry will connect successfully, cutting total search time. This is one of the safest and most impactful changes for invasion frequency.\r\n\r\nLowering it below 5 produces the opposite effect: the game cycles through its tiny list faster but has to restart the full search interval more often, which can actually make invasions feel slower in active sessions.",
		AdvancedDetails: "PARAMDEF SortID: 200 — 乱入先取得数 (NET_BREAKIN_PARAM)\r\nMemory offset: 0x70  |  Type: int32 (LittleEndian.Uint32)\r\nVanilla value: 5\r\nValidation: 1–20 casual, 1–MaxInt32 advanced\r\nNo cross-field dependencies.",
	},
	{
		Key: "breakInRequestAreaCount", View: ViewInvader,
		Label: "Area search count", Internal: "BreakInRequestAreaCount", Type: "int32",
		Advanced: false, Min: 1, Max: 20, AdvancedMin: 1, AdvancedMax: float64(math.MaxInt32),
		ShortDef: "Influences how broadly the server searches across the game's map regions when compiling your invasion candidate list. A higher value tells the server to look across more distinct geographic zones, which helps find targets in areas where fewer players are active.\r\nRaising it → broader geographic search; more candidates in less-populated late-game regions.\r\nLowering it → narrower search; fine for early-game high-population areas, but can produce very thin lists in end-game zones.",
		LongDef: "Elden Ring's map is divided into distinct geographic regions — Limgrave, Liurnia of the Lakes, Caelid, the Altus Plateau, and so on. When your client requests an invasion candidate list, this parameter appears to control how many of those regions the server searches through to build your list.\r\n\r\nWith the default value of 5, the server searches a limited number of zones. This works well in early-game areas like Limgrave where many players are actively invading, but can produce nearly empty lists in late-game regions like Farum Azula or Miquella's Haligtree where the active population is sparse. Raising this value instructs the server to search more zones, pulling candidates from a wider geographic area of the map.\r\n\r\nRaising it toward 10–15 is particularly useful for players who spend most of their time in end-game areas, or during off-peak hours when even popular areas are lightly populated.\r\n\r\nImportant caveat: FromSoftware deliberately obscured this field in their public parameter files (labelling it as unused padding), so its exact server-side behavior is inferred from community testing rather than confirmed documentation. Treat changes conservatively.",
		AdvancedDetails: "PARAMDEF SortID: 203 — labelled 'dummy8 pad[4]' in the public PARAMDEF to conceal it from standard editors (NET_BREAKIN_PARAM)\r\nMemory offset: 0x7C  |  Type: int32 (read as uint32, treated as signed)\r\nVanilla value: 5\r\nValidation: 1–20 casual, 1–MaxInt32 advanced\r\nNo cross-field dependencies. Exact server-side behavior is community-inferred, not officially documented.",
	},
	{
		Key: "breakInRequestIntervalTimeSec", View: ViewInvader,
		Label: "Search interval", Internal: "BreakInRequestIntervalTimeSec", Type: "float32",
		Advanced: false, Min: 2, Max: 30, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "The number of seconds the game waits between sending successive invasion search requests to the server. This is the cooldown between batches — shorter means more frequent searches.\r\nRaising it → longer gaps between batches; invasions become less frequent even when the server has eligible hosts.\r\nLowering it → the client checks for new hosts more often; invasions start faster when hosts become available.",
		LongDef: "After your client either exhausts its current list of candidates or a connection attempt times out, it pauses for this many seconds before sending a fresh search request to the matchmaking server. Think of it as the cooldown between rounds of searching.\r\n\r\nAt the game's default of 30 seconds, you can wait nearly half a minute between batches — which is why invasions feel sluggish even during active server periods. A player who just summoned a cooperator and became invasible will only appear in your next batch, and that batch might not arrive for up to 30 seconds.\r\n\r\nReducing this to 8–12 seconds means your client checks in with the server far more frequently, picking up hosts who just became available. At that cadence, a newly eligible host is likely to appear in your next batch within seconds rather than half a minute.\r\n\r\nGoing below 4 seconds provides diminishing returns: the network round-trip to the server takes a minimum amount of time regardless, and you'd be firing off requests faster than responses can meaningfully differ. 6–10 seconds is the practical sweet spot for aggressive invasion builds.",
		AdvancedDetails: "PARAMDEF SortID: 201 — 乱入リクエスト間隔[秒] (NET_BREAKIN_PARAM)\r\nMemory offset: 0x74  |  Type: float32\r\nVanilla value: 30.0 s\r\nValidation: 2–30 s casual, 1–999 s advanced\r\nThe server also has a minimum dispatch rate independent of this setting.",
	},
	{
		Key: "breakInRequestTimeOutSec", View: ViewInvader,
		Label: "Request timeout", Internal: "BreakInRequestTimeOutSec", Type: "float32",
		Advanced: false, Min: 3, Max: 20, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "How long your client waits for a single candidate host to respond and complete the connection before giving up on them and moving to the next entry in the list. If every host in the current list times out, the search interval begins again.\r\nRaising it → slow or distant connections get more time to establish; fewer false negatives, but failed attempts take longer to abandon.\r\nLowering it → dead or unresponsive hosts are dropped faster; the client cycles through the candidate list more quickly, but valid slow connections may be cut prematurely.",
		LongDef: "When your client picks a world from its candidate list and tries to invade it, both sides must complete a session handshake: your client reaches out, the host's game accepts the notification, and a peer-to-peer connection is established. This parameter is the maximum time your client will wait for that entire process to finish.\r\n\r\nIf the host's session is unreachable — their game closed, they died, the level-range check fails at the last moment, or their connection is too congested — the handshake stalls. After waiting this many seconds with no progress, your client abandons that particular host and tries the next entry in its list.\r\n\r\nRaising this value means you'll successfully connect to hosts who need more time. The cost is that when a connection truly fails, you spend longer waiting before giving up.\r\n\r\nLowering it makes your client more ruthless about abandoning stalled handshakes, which speeds up cycling through the list.",
		AdvancedDetails: "PARAMDEF SortID: 202 — 乱入リクエストタイムアウト時間[秒] (NET_BREAKIN_PARAM)\r\nMemory offset: 0x78  |  Type: float32\r\nVanilla value: 20.0 s\r\nValidation: 3–20 s casual, 1–999 s advanced",
	},
}
