package app


// ---------------------------------------------------------------------------
// Hunter params — NET_VISIT_PARAM + NET_EXTRA_PARAM
// 8 params: 7 basic (matching SaveForge), 1 advanced (not edited by SaveForge).
// Basic sorted: cooldown, list size, summon cap, search timing pair, area rates pair.
// ---------------------------------------------------------------------------

var hunterParams = []ParamMeta{
	{
		Key: "reloadVisitListCoolTime", View: ViewHunter,
		Label: "Visit list cooldown", Internal: "ReloadVisitListCoolTime", Type: "float32",
		Advanced: false, Min: 3, Max: 60, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "How long the game waits between search cycles when the Blue Cipher Ring is equipped. Each cycle asks the server whether there is an invaded world that needs a Hunter. A shorter cooldown means the game checks more frequently and dispatches you faster when a compatible world becomes available.\r\nRaising it → longer gaps between searches; you may miss short-lived invasions that resolve before your next check-in.\r\nLowering it → the game checks in with the server more often; you are dispatched closer to the moment an invasion begins nearby.",
		LongDef: "When you equip the Blue Cipher Ring, your game enters a continuous background search loop: every this-many-seconds, your client asks the matchmaking server whether there is an invaded world nearby that needs a Hunter to assist. If the server has a match ready and compatible with your character, you are automatically summoned in.\r\n\r\nAt the default 20 seconds, you check in with the server roughly 3 times per minute. During active PvP periods when invasions are common, this is frequent enough. But during the moments between invasions — when one just ended and a new one is about to begin — the 20-second gap can cause you to miss the window entirely, especially if the invader is eliminated quickly by the host and cooperators.\r\n\r\nReducing this cooldown makes the most difference in moderate-activity periods where invasions begin and end quickly. At 5–8 seconds, you are checking in nearly constantly and are much more likely to be dispatched within seconds of an invasion starting. The practical benefit diminishes below about 3 seconds because the server's own dispatch processing introduces a minimum effective latency regardless of how often you ask.\r\n\r\nRaising this value beyond the vanilla 20 seconds is rarely useful — it simply means you respond to invasions more slowly for no benefit.",
		AdvancedDetails: "PARAMDEF SortID: 600 — 指輪検索間隔[秒] (NET_VISIT_PARAM)\r\nMemory offset: 0x180  |  Type: float32\r\nVanilla value: 20 s\r\nValidation: 1–1000 s\r\nGoverns search loop for all Blue Cipher Ring variants. Distinct from Co-op Search Min/Max (0x190/0x194), which govern a separate randomized interval mechanism.",
	},
	{
		Key: "maxVisitListCount", View: ViewHunter,
		Label: "Visit list size", Internal: "MaxVisitListCount", Type: "int32",
		Advanced: false, Min: 1, Max: 20, AdvancedMin: 1, AdvancedMax: 50,
		ShortDef: "How many invaded worlds the server returns per Hunter search cycle. Analogous to Target List Size for invaders — a larger list gives you more candidates to try per search cycle, reducing wasted cycles in busy sessions.\r\nRaising it → more candidate worlds per request; better odds of finding a compatible, reachable world without needing a second search cycle.\r\nLowering it → fewer options per request; the game may exhaust its small list on incompatible or full worlds and have to restart the search cycle.",
		LongDef: "Each time your Hunter search cycle fires, your client receives a list of invaded worlds it could potentially enter as a defender. This parameter controls the maximum length of that list. Your client then tries each entry in sequence — checking that you meet the level requirements, that the world isn't already at player capacity, and that a peer-to-peer connection can be established — until one succeeds or the list is exhausted.\r\n\r\nWith the vanilla value of 5, you receive 5 candidates per cycle. If all 5 are incompatible (wrong level range, full party, invader already dead) or unreachable (host disconnected, area changed), the cooldown begins again without you being dispatched anywhere. A larger list gives you more attempts before that cycle is wasted.\r\n\r\nThis is particularly valuable during PvP-heavy sessions when many invasions are happening simultaneously and the server has many invaded worlds to report — but many of those worlds may not be compatible with your specific character. A list of 15 or 20 gives you far more chances to find a match in each cycle than a list of 5.\r\n\r\nThis parameter directly mirrors the role of Target List Size in the invasion system: both control the 'candidates per search request' metric for their respective roles, and both benefit from being raised in active PvP environments.",
		AdvancedDetails: "PARAMDEF SortID: 603 — 指輪検索先取得数 (NET_VISIT_PARAM)\r\nMemory offset: 0x18C  |  Type: int32 (stored as u32)\r\nVanilla value: 5\r\nValidation: 1–50 (all modes)\r\nDirect analog to MaxBreakInTargetListCount (0x70) for the Hunter role.",
	},
	{
		Key: "maxCoopBlueSummonCount", View: ViewHunter,
		Label: "Co-op blue summon cap", Internal: "MaxCoopBlueSummonCount", Type: "int32",
		Advanced: false, Min: 1, Max: 5, AdvancedMin: 1, AdvancedMax: 10,
		ShortDef: "The client-side maximum number of Hunter-role Blue Phantoms allowed in a single world at once. In standard online play, the game server enforces its own session limit that is the actual binding constraint — this parameter only matters if you are using a custom server that also lifts its cap.\r\nRaising it → removes the client's local check; has no visible effect in standard online play since the server cap takes precedence.\r\nLowering it → artificially restricts Blue Phantom presence on the client side, potentially below the server's own limit.",
		LongDef: "This parameter sets how many Hunter-role phantoms your game client will allow in the world at once before refusing additional connections. With the default value of 2, your client code rejects more than 2 Blue Phantoms regardless of what the server might send.\r\n\r\nHowever, this client-side cap is almost never what limits Hunter numbers in actual gameplay. FromSoftware's matchmaking servers enforce their own per-session limit, and that server-side cap is the binding constraint for standard online play. Raising this parameter simply removes the client's local check — the server will still cap the actual number of Blue Phantoms at its own limit, which cannot be raised by editing the save file alone.\r\n\r\nThe practical use cases for raising this value are limited to: custom server environments where the server cap has also been raised, or research setups where you want to understand client-side vs server-side behavior differences. For standard play, any value of 2 or above produces identical results.\r\n\r\nLowering below 2 artificially restricts the game below its intended behavior and reduces co-op effectiveness for no practical benefit.",
		AdvancedDetails: "PARAMDEF SortID: 601 — 救援青霊出現数上限 (NET_VISIT_PARAM)\r\nMemory offset: 0x184  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 2\r\nValidation: 1–10 (all modes)\r\nThe server enforces a separate, independent cap. Client values above that server cap are silently no-ops in standard online play.",
	},
	{
		Key: "reloadSearchCoopBlueMin", View: ViewHunter,
		Label: "Co-op search min", Internal: "ReloadSearchCoopBlueMin", Type: "float32",
		Advanced: false, Min: 3, Max: 120, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "The lower bound of a randomized wait time between Hunter search cycles. The game picks a random interval between this minimum and Co-op Search Max before each search, which prevents every active Hunter from hitting the server simultaneously.\r\nRaising it → even the fastest searches wait longer; reduces dispatch responsiveness for everyone with the ring equipped.\r\nLowering it → the shortest possible waits become shorter; marginally improves best-case dispatch speed, though the maximum dominates the average.",
		LongDef: "Rather than firing on a fixed schedule, the Hunter search system uses a randomized wait: the game picks a random number of seconds between this minimum and the Co-op Search Max, then waits that long before running the next search cycle. The randomization exists specifically to spread server requests over time — if every Blue Cipher Ring player fired searches on exactly the same cadence, they would all hit the server at the same moments, creating artificial load spikes.\r\n\r\nThe minimum sets the floor of that random range. Practically, reducing the minimum from 30 seconds to 3 seconds changes the fastest possible wait — but since the game picks uniformly between min and max, the average is (min + max) ÷ 2. At vanilla settings (30 min, 180 max), the average wait is 105 seconds. Setting min to 3 and leaving max at 180 gives an average of 91.5 seconds — a modest improvement.\r\n\r\nThe most effective approach for faster dispatch: reduce both minimum and maximum together. Setting both to a small range like 3–15 seconds gives an average wait of 9 seconds, a dramatic improvement over vanilla. Changing only the minimum while leaving the maximum at 180 has limited impact because the maximum drives the average.\r\n\r\nThe minimum must never exceed the maximum — if it does, the game's behavior in selecting a random interval becomes undefined.",
		AdvancedDetails: "PARAMDEF SortID: 604 — 救援青霊リロード時間 最小[sec] (NET_VISIT_PARAM)\r\nMemory offset: 0x190  |  Type: float32\r\nVanilla value: 30 s\r\nValidation: 1–999 s\r\nCross-field constraint: must be ≤ ReloadSearchCoopBlueMax (0x194). The actual per-cycle wait is drawn from Uniform(min, max). ValidateNetworkParams enforces the min ≤ max invariant.",
	},
	{
		Key: "reloadSearchCoopBlueMax", View: ViewHunter,
		Label: "Co-op search max", Internal: "ReloadSearchCoopBlueMax", Type: "float32",
		Advanced: false, Min: 10, Max: 300, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "The upper bound of the randomized wait time between Hunter search cycles. This is the most impactful of the two search interval parameters — because the game picks uniformly between min and max, the maximum determines the longest possible waits and dominates the average search frequency.\r\nRaising it → longer worst-case waits; Hunter dispatch becomes slower and more unpredictable.\r\nLowering it → shorter maximum waits; the single most effective lever for increasing Hunter dispatch frequency.",
		LongDef: "This is the ceiling of the random wait interval used between Hunter search cycles, paired with Co-op Search Min. Because the game picks uniformly from the range [min, max], the average wait per cycle is (min + max) ÷ 2. The maximum therefore has an outsized influence: at vanilla values (30 min, 180 max), the average is 105 seconds. Cutting the maximum to 60 seconds — while leaving the minimum at 30 — drops the average to 45 seconds, more than halving the expected wait.\r\n\r\nReducing the maximum is the single most impactful change you can make for Hunter dispatch speed. It eliminates the worst-case long waits and brings the average down significantly even without touching the minimum.\r\n\r\nFor the fastest dispatch, reduce both minimum and maximum together to a small range (e.g., 3–15 s). This gives an average of 9 seconds between searches — roughly 6x faster than vanilla — while preserving the randomization that prevents server flooding.\r\n\r\nRaising the maximum beyond 180 seconds essentially means you might wait 3+ minutes between search cycles on a bad roll, making Hunter play feel entirely passive and unreliable.\r\n\r\nThe maximum must always be ≥ the minimum. Setting them equal removes the randomness and creates a fixed-interval search.",
		AdvancedDetails: "PARAMDEF SortID: 605 — 救援青霊リロード時間 最大[sec] (NET_VISIT_PARAM)\r\nMemory offset: 0x194  |  Type: float32\r\nVanilla value: 180 s\r\nValidation: 1–999 s\r\nCross-field constraint: must be ≥ ReloadSearchCoopBlueMin (0x190). ValidateNetworkParams enforces this invariant.",
	},
	{
		Key: "allAreaSearchRateCoopBlue", View: ViewHunter,
		Label: "Co-op all-area rate (%)", Internal: "AllAreaSearchRateCoopBlue", Type: "int32",
		Advanced: false, Min: 0, Max: 100, AdvancedMin: 0, AdvancedMax: 100,
		ShortDef: "The probability (0–100%) that a given Hunter search cycle looks for invaded worlds across the entire map rather than restricting itself to worlds geographically near you. At 0% searches are purely local; at 100% every search is global.\r\nRaising it → more searches go global; you find invaded worlds even when your immediate region is quiet, at the cost of potentially higher latency matches.\r\nLowering it → searches focus on nearby worlds; better connection quality for matches but you may miss invasions in distant areas when local activity is low.",
		LongDef: "By default, Hunter searches have a geographic bias — the server prefers to match you with invaded worlds in map regions physically close to where your character currently is. This tends to produce lower-latency connections since nearby players typically share internet infrastructure. However, if no invasions are happening in your region, a local-only search will consistently come up empty.\r\n\r\nThis parameter introduces a dice roll on each search cycle: if the random result falls below this percentage, the search goes global and includes invaded worlds anywhere on the map regardless of your location. If the result falls at or above this percentage, the search stays local.\r\n\r\nAt the vanilla value of 30%, roughly one in three searches is global. During quiet periods this is often insufficient — you may go through many consecutive local-only searches finding nothing before a global search finally runs. Raising this value toward 60–80% means most searches cover the full map, dramatically improving dispatch rates during low-activity periods.\r\n\r\nThe tradeoff: a global match may pair you with a player on the other side of the world, with a noticeably higher ping. For players who prioritize being dispatched as often as possible regardless of connection quality, higher values make sense. For players who care about a smooth, low-latency experience, lower values preserve that at the cost of fewer dispatches.",
		AdvancedDetails: "PARAMDEF SortID: 730 — 全域検索率：救援青霊 (NET_EXTRA_PARAM)\r\nMemory offset: 0x1D8  |  Type: u8 (1 byte), stored as int32 in the struct\r\nVanilla value: 30\r\nValidation: 0–100 (strict percentage)\r\nThe three all-area rate bytes are stored consecutively: 0x1D8 (CoopBlue), 0x1D9 (VsBlue), 0x1DA (BellGuard).",
	},
	{
		Key: "allAreaSearchRateVsBlue", View: ViewHunter,
		Label: "Hunter all-area rate (%)", Internal: "AllAreaSearchRateVsBlue", Type: "int32",
		Advanced: false, Min: 0, Max: 100, AdvancedMin: 0, AdvancedMax: 100,
		ShortDef: "The global-search probability for the 'retribution' or 'vengeful' Hunter variant — as distinct from the general co-op assist search. In Elden Ring this likely corresponds to Blue Cipher Ring responses triggered by an active invasion, as opposed to a White Cipher Ring co-op call.\r\nRaising it → more searches for active-invasion scenarios go global; you find invaded worlds in distant regions more often in this specific trigger context.\r\nLowering it → searches for this trigger type stay more geographically focused.",
		LongDef: "The Blue Cipher Ring can be triggered in two conceptually distinct ways: as a general co-op assist (responding to a host who actively called for help via the White Cipher Ring) and as a retribution or 'vengeful' response when an invasion is actively occurring nearby. This parameter applies specifically to the retribution trigger.\r\n\r\nThe mechanic works identically to Co-op All-Area Rate: on each relevant search cycle, a percentage roll determines whether the search goes global or stays local. The distinction between 'co-op blue' and 'vs blue' in the game's internal data suggests FromSoftware intended these two triggers to potentially have different search behaviors — different default biases toward local vs global, or different priority levels.\r\n\r\nIn Elden Ring specifically, the functional separation between these two trigger types may be less clear-cut than in earlier games in the series, where covenant-based distinctions (Way of Blue vs Blue Sentinels in Dark Souls 3) were more prominent in the player-facing design. Community testing on this specific parameter's isolated effect in ER is limited.\r\n\r\nFor most users, keeping this in line with Co-op All-Area Rate is a sensible default. Setting it to different values allows fine-tuning of how aggressively each type of Hunter trigger searches globally.",
		AdvancedDetails: "PARAMDEF SortID: 730 — 全域検索率：報復青霊 (NET_EXTRA_PARAM)\r\nMemory offset: 0x1D9  |  Type: u8 (1 byte), stored as int32 in struct\r\nVanilla value: 30\r\nValidation: 0–100\r\nThe '報復青霊' (retribution/revenge blue spirit) designation likely originates from DS3's Blue Sentinels covenant. In ER the trigger conditions may differ from earlier titles.",
	},
	// --- Advanced params (not edited by SaveForge) ---
	{
		Key: "allAreaSearchRateBellGuard", View: ViewHunter,
		Label: "Bell-guard all-area rate (%)", Internal: "AllAreaSearchRateBellGuard", Type: "int32",
		Advanced: true, Min: 0, Max: 100, AdvancedMin: 0, AdvancedMax: 100,
		ShortDef: "The global-search probability for a third phantom variant called 'bell guardian' in the game's internal data. This role has legacy origins from Dark Souls 2 and its exact behavior in Elden Ring is uncertain — it may be vestigial or tied to an undocumented mechanic.\r\nRaising it → increases global search rate for whatever scenario triggers this phantom type; effect in ER is unconfirmed.\r\nLowering it → restricts that search to local results; equally unconfirmed in its practical effect.",
		LongDef: "In Dark Souls 2, the 'Bell Keepers' were a PvP covenant whose members were automatically summoned to defend specific bell towers from trespassers. The system worked as an early automated invasion mechanic tied to geographic locations rather than general PvP flags. The 'bell guardian' designation in Elden Ring's parameters is a direct descendant of that system — the same internal name exists in the data.\r\n\r\nElden Ring does not have an obvious bell guardian mechanic in its player-facing content. The game has no bell towers with designated defenders, no Bell Keeper covenant, and no item in the game explicitly described as triggering this phantom type. Despite this, the parameter exists in the regulation data and appears to be a live value (not zeroed out), suggesting it either maps to some undocumented mechanic or remains from legacy code that was not fully removed.\r\n\r\nThe parameter's position — as the third of three consecutive all-area rate bytes — means it shares the same fundamental search mechanic as the other two. Adjusting it alongside the other all-area rates is technically harmless, and setting it to match the co-op or retribution rates is a reasonable default.\r\n\r\nThis parameter is primarily exposed here for completeness and for users who want comprehensive control over all available matchmaking parameters, particularly in custom server environments where this mechanic might be differently configured.",
		AdvancedDetails: "PARAMDEF SortID: 730 — 全域検索率：鐘守灰霊 (NET_EXTRA_PARAM)\r\nMemory offset: 0x1DA  |  Type: u8 (1 byte), stored as int32 in struct\r\nVanilla value: 30\r\nValidation: 0–100\r\nThe '鐘守灰霊' (bell guardian spirit) name connects to DS2's Bell Keeper covenant.\r\nIn-game trigger conditions in ER: unconfirmed by community testing as of this writing.",
	},
}

