package app

import "math"


// ---------------------------------------------------------------------------
// Summoning Sign params — NET_SUMMON_SIGN_PARAM + NET_COMMON_PARAM
// 12 params: 7 basic (matching SaveForge), 5 advanced (not edited by SaveForge).
// Basic sorted: refresh rate, pool params (total/cell/cap), sync timing.
// ---------------------------------------------------------------------------

var signParams = []ParamMeta{
	{
		Key: "reloadSignIntervalTime2", View: ViewSign,
		Label: "Sign refresh interval", Internal: "ReloadSignIntervalTime2", Type: "float32",
		Advanced: false, Min: 5, Max: 120, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "How often the game downloads a completely fresh list of summon signs from the server while you're actively moving through an area. This is the primary control for how responsive the sign pool feels — shorter means new signs appear faster and expired signs vanish sooner.\r\nRaising it → signs update less frequently; familiar in quiet areas, frustrating in busy ones where signs appear long after they're placed.\r\nLowering it → the sign list feels live and current; new phantoms' signs appear quickly, expired signs vanish promptly.",
		LongDef: "Summon signs exist in two places simultaneously: on FromSoftware's matchmaking server, and in a local cache inside your game client. Your client periodically discards its entire local list and downloads a fresh one from the server — this full refresh is what causes signs to 'pop in' on your screen rather than appearing the instant a phantom places them.\r\n\r\nThis parameter controls how often that full refresh happens during normal active play — when you're walking through an area, standing near signs, or approaching a boss. At the game's default of 60 seconds, you might wait nearly a full minute before a freshly-placed phantom sign appears in your world. In a busy co-op area with many phantoms placing and removing signs constantly, that lag makes the experience feel stale.\r\n\r\nLowering this value directly reduces that wait. At 10–20 seconds, the sign pool feels noticeably more alive: new signs show up within moments of being placed, and signs from phantoms who disconnected vanish quickly rather than lingering as false targets. The cost is increased server traffic, since your client is making full refresh requests more often. Values below 5 seconds push into territory where you're refreshing faster than the server can provide meaningfully different data.\r\n\r\nRaising the value beyond 60 seconds works fine in quiet areas where sign activity is slow, but creates a poor experience anywhere active co-op is happening.",
		AdvancedDetails: "PARAMDEF SortID: 103 — 召喚サイン再取得待機時間[秒] (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x1C  |  Type: float32\r\nVanilla value: 60 s\r\nValidation: 1–1000 s\r\nThis is the 'active' refresh timer. The companion 'inactive' timer (SortID 102, Inactive Refresh Interval) is at offset 0x18 and is an Advanced parameter.",
	},
	{
		Key: "reloadSignTotalCount", View: ViewSign,
		Label: "Sign pool (total)", Internal: "ReloadSignTotalCount", Type: "int32",
		Advanced: false, Min: 5, Max: 64, AdvancedMin: 1, AdvancedMax: float64(math.MaxInt32),
		ShortDef: "The maximum number of summon signs your game stores in its local cache after each server refresh. This is the size of the sign 'database' you can see at any one moment — more signs cached means more options visible on the ground simultaneously.\r\nRaising it → more signs visible at once; crucial in dense co-op areas where the default 20 leaves many valid phantoms invisible.\r\nLowering it → fewer signs cached; redundant in quiet areas but actively harmful in busy ones.",
		LongDef: "When your client downloads a sign list from the server, it doesn't show every sign the server knows about in your area. Instead, it stores up to this many signs locally and displays all of them as golden or red marks on the ground.\r\n\r\nAt the vanilla default of 20, you see at most 20 signs on the ground at once — even in popular co-op spots near boss fog gates where dozens of players may have active signs. The server has a much larger record, but your client only asks for and stores a limited slice.\r\n\r\nRaising this to 40 or 64 means those densely-populated areas show many more options without requiring additional server requests — you're simply holding a larger local cache. The difference is most noticeable just before major bosses in the game's early-to-midgame, where sign density is highest.\r\n\r\nThis value must stay within the invariant: Sign Pool (Per Cell) ≤ Sign Pool (Total) ≤ Sign Buffer Cap. Adjust the Buffer Cap first if you want to raise this beyond its current limit.",
		AdvancedDetails: "PARAMDEF SortID: 105 — 召喚サイン所持可能数上限(全体) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x20  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 20\r\nValidation: 1–128\r\nCross-field constraints: must be ≥ ReloadSignCellCount (0x24) and ≤ SingGetMax (0x60). Breaking these invariants produces inconsistent pool behavior.",
	},
	{
		Key: "reloadSignCellCount", View: ViewSign,
		Label: "Sign pool (per cell)", Internal: "ReloadSignCellCount", Type: "int32",
		Advanced: false, Min: 1, Max: 32, AdvancedMin: 1, AdvancedMax: 99,
		ShortDef: "The maximum signs your game will cache from any single spatial matchmaking cell. The world is divided into a grid of zones, and this cap prevents one densely populated zone from monopolizing your entire sign pool, ensuring you see signs from multiple geographic locations.\r\nRaising it → a single dense area can contribute more signs to your pool; useful if you specifically want signs from one concentrated location.\r\nLowering it → forces the pool to draw from more cells simultaneously; better geographic diversity in the sign list.",
		LongDef: "The game's multiplayer matchmaking divides the world into a spatial grid of zones called 'cells'. Multiple cells surround the player at any given time. When fetching signs, the client collects results from all the cells in its search radius. Without a per-cell limit, a single very densely populated cell — say, a popular boss approach with hundreds of active phantoms — could fill your entire sign pool, leaving you with a homogeneous list from one tiny area.\r\n\r\nThis parameter prevents that by imposing a per-cell cap. Even if a cell has 100 available signs, your client will only take at most this many from it before moving to the next cell. This ensures your sign list represents multiple geographic locations, which is particularly important in areas where player density varies significantly between adjacent zones.\r\n\r\nThe relationship to other pool parameters: per-cell cap ≤ total pool cap ≤ server buffer cap. A per-cell cap at 50–75% of the total pool generally provides a good balance between density-area coverage and geographic diversity.\r\n\r\nRaising this value beyond the total pool cap has no practical effect since the total pool cap is the binding constraint.",
		AdvancedDetails: "PARAMDEF SortID: 106 — 召喚サイン所持可能数上限(セル) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x24  |  Type: int32 (PARAMDEF notes 'actually u8' for value range; stored as 32-bit)\r\nVanilla value: 10\r\nValidation: 1–99\r\nCross-field constraint: must be ≤ ReloadSignTotalCount (0x20). ValidateNetworkParams enforces this.",
	},
	{
		Key: "singGetMax", View: ViewSign,
		Label: "Sign buffer cap", Internal: "SingGetMax", Type: "int32",
		Advanced: false, Min: 10, Max: 96, AdvancedMin: 1, AdvancedMax: 128,
		ShortDef: "The hard ceiling on how many signs the server will return in a single fetch request. This is the server-side counterpart to Sign Pool (Total) — if this value is smaller than the pool, the pool can never be fully filled regardless of server activity.\r\nRaising it → the server can return larger batches; necessary before raising Sign Pool (Total) beyond the current cap.\r\nLowering it → the server returns fewer signs per request; Sign Pool (Total) becomes effectively capped at this lower value even if set higher.",
		LongDef: "When your client asks the server for signs, the server's response is bounded by this value. No matter how large your local Sign Pool (Total) is configured, the server will never send back more than this many signs in a single response.\r\n\r\nThis creates a strict dependency: Sign Pool (Total) is the size of your local cache, and Sign Buffer Cap is the maximum the server will hand you to fill it. If you set Sign Pool (Total) to 64 but leave the Sign Buffer Cap at the default of 32, your pool can only ever be half full — the server caps each response at 32 signs regardless of how large your local cache is.\r\n\r\nThe invariant is always: per-cell cap ≤ total pool ≤ buffer cap. When raising sign visibility, raise the Buffer Cap first, then the total pool, then the per-cell cap to match.\r\n\r\nNote: the game server itself may impose an additional independent cap beyond this client-defined value. If you raise this very high and see no improvement in sign counts, you may have hit the server's own ceiling.",
		AdvancedDetails: "PARAMDEF SortID: 122 — サイン取得上限 (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x60  |  Type: int32\r\nVanilla value: 32\r\nValidation: 1–128\r\nCross-field constraint: must be ≥ ReloadSignTotalCount (0x20). ValidateNetworkParams enforces this.\r\nNote: the game server may impose its own independent cap. Client-side values above that server cap are silently clamped server-side.",
	},
	{
		Key: "updateSignIntervalTime", View: ViewSign,
		Label: "Sign upload interval", Internal: "UpdateSignIntervalTime", Type: "float32",
		Advanced: false, Min: 5, Max: 120, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "How often your game re-registers your own placed summon sign with the server, confirming it is still valid. Without periodic re-registration, the server may expire your sign and remove it from other players' lists even though you are still waiting to be summoned.\r\nRaising it → less frequent heartbeats; sign may appear on fewer players' screens over time as it ages on the server.\r\nLowering it → your sign stays freshly registered; much lower risk of silently expiring during long waits.",
		LongDef: "When you place a summon sign on the ground, your game doesn't simply set it once and forget it. Signs on the FromSoftware server have a limited validity period — if the server doesn't hear from your client confirming the sign is still active, it eventually drops it from its records. Other players' lists then stop showing your sign even though you're still standing there, sorcerer's staff in hand, wondering why nobody is summoning you.\r\n\r\nThis parameter controls how frequently your client sends that 'I'm still here' confirmation message — think of it as a heartbeat for your own sign. Every this-many-seconds, your game pings the server to keep your sign alive.\r\n\r\nAt 30 seconds (vanilla), you're sending a heartbeat twice per minute. That's generally sufficient, but in long waits — sitting near a fog gate for 10+ minutes hoping for a summon — the risk of a heartbeat being dropped or delayed by network conditions increases. Reducing this to 10–15 seconds provides more frequent confirmations and meaningfully reduces the chance of your sign expiring silently.\r\n\r\nRaising it beyond 30 seconds saves a small amount of server traffic but increases the risk that your sign disappears from other players' views during extended waits.",
		AdvancedDetails: "PARAMDEF SortID: 107 — 召喚サイン更新待機時間[秒] (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x28  |  Type: float32\r\nVanilla value: 30 s\r\nValidation: 1–1000 s\r\nThis governs re-registration of the player's own sign specifically. Distinct from SignDownloadSpan (0x64) and SignUpdateSpan (0x68), which handle bulk background data synchronization.",
	},
	{
		Key: "signDownloadSpan", View: ViewSign,
		Label: "Sign download span", Internal: "SignDownloadSpan", Type: "float32",
		Advanced: false, Min: 5, Max: 120, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "The minimum gap between background sign data downloads — the fine-grained 'trickle update' rate that runs between full list refreshes. Shorter spans mean individual sign changes propagate to your screen faster, creating a more continuously updated feel.\r\nRaising it → longer gaps between trickle updates; sign changes only visible after full refreshes, making the pool feel more static.\r\nLowering it → individual sign changes appear more quickly between full refreshes; smoother overall sign experience.",
		LongDef: "Elden Ring keeps sign data current using two overlapping mechanisms. The first (Sign Refresh Interval) is a full reset: the client wipes its local sign list and downloads everything fresh. The second is a background trickle: the client periodically fetches updates to individual signs — new signs that just appeared, signs that were removed — without rebuilding the entire list from scratch.\r\n\r\nThis parameter controls the minimum time between those background trickle downloads. Think of the full refresh as a snapshot and the trickle as the continuous updates between snapshots. Reducing the trickle span means individual changes propagate faster during the gap between full refreshes, so the sign list feels more continuously current rather than jumping all at once every 60 seconds.\r\n\r\nIn practical terms: the Sign Refresh Interval is what causes a wave of new signs to appear all at once after a long wait, while the download span is what causes individual signs to appear between those full refreshes. For heavily co-op focused sessions, reducing both values together produces the most responsive sign experience.\r\n\r\nRaising this span beyond 30 seconds creates a noticeably more 'batchy' update pattern where signs change only during full refreshes.",
		AdvancedDetails: "PARAMDEF SortID: 123 — サインダウンロードスパン (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x64  |  Type: float32\r\nVanilla value: 30 s\r\nValidation: 1–1000 s\r\nWorks in conjunction with ReloadSignIntervalTime2 (full refresh, 0x1C) and SignUpdateSpan (upload direction, 0x68).",
	},
	{
		Key: "signUpdateSpan", View: ViewSign,
		Label: "Sign upload span", Internal: "SignUpdateSpan", Type: "float32",
		Advanced: false, Min: 5, Max: 120, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "The minimum gap between background sign data uploads — the outgoing counterpart to Sign Download Span. This controls how often your client pushes sign-related state back to the server, keeping the server's record of your session current.\r\nRaising it → your client's outgoing updates to the server become less frequent; the server's view of your local sign activity grows stale.\r\nLowering it → your client reports changes to the server more often; the server has a more accurate picture of your session, which can improve the experience for players searching for signs near you.",
		LongDef: "Just as the client periodically downloads sign data from the server (Sign Download Span), it also periodically uploads its local state back. This upload direction matters because the server's database needs to stay accurate: if signs are being placed, removed, or rated in your area, the server needs to hear about it in order to accurately inform other players who are searching.\r\n\r\nFor most players the practical impact of this parameter is subtle — it primarily affects the direction of data flow rather than what you directly see on screen. Download parameters govern what you see; this governs what you contribute back. Lowering it keeps the server's picture of your session more current, which can indirectly improve the experience for other players searching for signs near your location.\r\n\r\nIn a fast-paced co-op session where summons are happening quickly and many players are placing and removing signs, reducing both download and upload spans together produces the most synchronized experience for everyone involved.\r\n\r\nRaising this significantly — to 120 seconds or more — makes your client report outgoing changes very rarely, which can create lag between local events and other players' ability to see them reflected in their sign lists.",
		AdvancedDetails: "PARAMDEF SortID: 124 — サインアップロードスパン (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x68  |  Type: float32\r\nVanilla value: 60 s\r\nValidation: 1–1000 s\r\nUpload counterpart to SignDownloadSpan (0x64). Distinct from UpdateSignIntervalTime (0x28), which handles re-registration of the player's own placed sign specifically.",
	},
	// --- Advanced params (not edited by SaveForge) ---
	{
		Key: "summonTimeoutTime", View: ViewSign,
		Label: "Summon timeout", Internal: "SummonTimeoutTime", Type: "float32",
		Advanced: true, Min: 10, Max: 600, AdvancedMin: 1, AdvancedMax: 999,
		ShortDef: "Sets the maximum time the game allows for a summon to complete after a host touches a phantom's sign. If the connection doesn't establish within this window, the attempt is cancelled and the sign returns to the ground.\r\nRaising it → slow or trans-regional connections get more time; fewer failed summons for distant players, but stuck loading screens last longer when a connection truly can't establish.\r\nLowering it → failed summon attempts resolve faster; less time staring at the loading wheel, but legitimate slow connections may be cut before they finish.",
		LongDef: "When a host steps on a summon sign, both their game and the phantom's game begin a handshaking process: they verify compatibility, negotiate a peer-to-peer connection, and start loading the phantom into the host's world. This entire process takes time, and this parameter defines the absolute maximum it's allowed to take.\r\n\r\nYou've likely experienced this from both sides: you accept a sign and both players see the spinning loading indicator for an awkwardly long time before it fails with no explanation. That's this timer expiring. When it does, the sign silently reappears on the ground and both players are left wondering what happened.\r\n\r\nThe vanilla value is 45 seconds. Most successful summons complete in 5–20 seconds, so 45 s already provides comfortable room for same-region and typical cross-regional connections. Connections that take longer than 30–40 seconds are almost always genuinely failing due to firewalls, network incompatibility, or the host having moved or died.\r\n\r\nLowering this value makes failure cases resolve faster, reducing the time spent staring at a stuck loading screen. The trade-off is that connections in the 15–45 second window — which are possible but rare for high-latency cross-continental sessions — may be cut before they finish. Raising it gives those marginal connections more time to succeed, but also extends every failed attempt proportionally.",
		AdvancedDetails: "PARAMDEF SortID: 2 — 召喚タイムアウト時間[秒] (NET_COMMON_PARAM — shared across all summoning types, not sign-specific)\r\nMemory offset: 0x08  |  Type: float32\r\nVanilla value: 45 s (confirmed from actual PS4 save file)\r\nValidation: 10–600 s casual, 1–999 s advanced",
	},
	{
		Key: "reloadSignIntervalTime1", View: ViewSign,
		Label: "Inactive refresh interval", Internal: "ReloadSignIntervalTime1", Type: "float32",
		Advanced: true, Min: 0, Max: 120, AdvancedMin: 0, AdvancedMax: 999,
		ShortDef: "Controls how often the game refreshes its local sign list while you are away from signs — in combat, exploring, or otherwise not in an active summoning context. A value of 0 (the game's own shipped default) means there is no separate inactive timer: the active refresh rate applies at all times regardless of context.\r\nSetting to 0 → vanilla behaviour; the active refresh rate (Sign Refresh Interval) is used in all states.\r\nRaising above 0 → enables a slower background refresh distinct from the active rate; useful if you want fast active refreshes without hammering the server during exploration.",
		LongDef: "The PARAMDEF defines two separate sign refresh timers — one for when you are actively engaging with the sign pool, and this one for when you are not. In practice the vanilla game ships with 0 at this field, which almost certainly means 'disabled: use the active refresh timer in all states.' The game does not distinguish between active and inactive contexts by default.\r\n\r\nIf you leave this at 0, the Sign Refresh Interval you set applies continuously — whether you are standing next to signs or fighting a boss on the other side of the level. This is the simplest and most predictable behaviour, and it is what the game does out of the box.\r\n\r\nSetting a non-zero value here enables a two-speed system: a faster active rate when near signs, and a slower background rate controlled by this parameter when you are away. For example, active rate of 10 s and inactive rate of 60 s means fast refresh near fog gates but only one background pull per minute while exploring — lower server traffic without making the sign list feel stale when you return to a summoning area.\r\n\r\nFor most users, leaving this at 0 and only tuning Sign Refresh Interval is the right choice. Only set a non-zero value here if you specifically want to separate the background and active refresh rates.",
		AdvancedDetails: "PARAMDEF SortID: 102 — 召喚サイン再取得待機時間(非活性)[秒] (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x18  |  Type: float32\r\nActual shipped regulation value: 0 (PARAMDEF lists default = 1 but the regulation ships 0)\r\nValidation: 0–1000 s  |  0 is explicitly valid — means 'use active timer (reloadSignIntervalTime2)'\r\nCompanion to ReloadSignIntervalTime2 (active timer, offset 0x1C).",
	},
	{
		Key: "signCellRangeH", View: ViewSign,
		Label: "Cell range (horizontal)", Internal: "SignCellRangeH", Type: "int32",
		Advanced: true, Min: 1, Max: 5, AdvancedMin: 1, AdvancedMax: 10,
		ShortDef: "Determines how wide the horizontal search radius is when fetching summon signs. A value of 1 searches only your immediate spatial cell; each step outward adds another ring of surrounding cells, exponentially expanding the geographic area from which signs are drawn.\r\nRaising it → dramatically more signs from a wider geographic area; essential in open-world zones where players spread out across cells.\r\nLowering it to 1 → only signs from your immediate cell; fine in tight dungeon corridors, limiting in open areas.",
		LongDef: "The game world is divided into a three-dimensional grid of spatial cells for matchmaking purposes. When fetching signs, the server searches outward from the player's current position using these range parameters to determine which cells to include.\r\n\r\nWith the vanilla value of 1, only the single cell you are standing in is searched. Raise it to 2 and you search your cell plus one ring of cells surrounding it — roughly 9 cells in the horizontal plane (a 3×3 grid). Raise to 3 and you get a 5×5 grid, 25 cells. Each step outward multiplies the searched area significantly.\r\n\r\nRaising horizontal range is most impactful in wide open areas like Limgrave, Liurnia, or the Mountaintops of the Giants, where players are naturally spread across multiple cells and a narrow search misses most of them. In tight dungeon corridors or small legacy dungeons, adjacent cells often have few players anyway, so raising range matters less.\r\n\r\nCritically: a wider search finds more signs, but you need more cache space to hold them. Always increase Sign Pool (Total) and Sign Buffer Cap in proportion when raising cell range, otherwise the additional cells are searched but the results are silently truncated to fit your existing cache.",
		AdvancedDetails: "PARAMDEF SortID: 113 — 召喚サイン取得セル範囲(水平) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x3C  |  Type: int32 (stored as u32 — 4 bytes despite PARAMDEF note 'actually u8' for value range)\r\nVanilla value: 1\r\nValidation: 1–5 casual, 1–10 advanced\r\nLayout verification: 3 u32 fields × 4 B (0x3C/0x40/0x44) + 6 f32 keyword-scale fields × 4 B (0x48–0x5F) = 36 B → SingGetMax at 0x60 ✓",
	},
	{
		Key: "signCellRangeUp", View: ViewSign,
		Label: "Cell range (upward)", Internal: "SignCellRangeUp", Type: "int32",
		Advanced: true, Min: 1, Max: 5, AdvancedMin: 1, AdvancedMax: 10,
		ShortDef: "The upward component of the spatial search radius — how many cell layers above the player's current position are included when fetching signs. Critical in vertically complex areas where players on upper floors would otherwise miss each other's signs.\r\nRaising it → signs from higher floors and elevated positions become visible; essential in multi-level areas.\r\nLowering it to 1 → only signs from your current vertical cell; players one floor above you are invisible in the sign pool.",
		LongDef: "Elden Ring's world has significant vertical complexity — Leyndell, Raya Lucaria, Elphael Brace of the Haligtree, and many dungeons span multiple floors with meaningful elevation differences. The matchmaking cell grid extends in three dimensions, and this parameter controls how many cell layers above the player are searched.\r\n\r\nWith the vanilla value of 1, a host standing at the bottom of Raya Lucaria Academy cannot see signs from a phantom standing on the roof — they occupy different vertical cells. Raising this value bridges those vertical gaps, allowing the sign search to encompass floors above the player's position.\r\n\r\nThis is particularly impactful in: tall towers and multi-story ruins (Stormveil Castle, Raya Lucaria), the transition zones between surface and underground areas (Altus Plateau above / Leyndell below), and Elphael Brace of the Haligtree which has extreme vertical layering across a single area.\r\n\r\nThe same pool-size rule applies: raising the cell range finds more signs from a wider volume, but Sign Pool (Total) and Sign Buffer Cap must be large enough to accommodate the increased results, otherwise the additional cells are searched but results are truncated.",
		AdvancedDetails: "PARAMDEF SortID: 114 — 召喚サイン取得セル範囲(上方向) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x40  |  Type: int32 (stored as u32 — same 4-byte storage note as SignCellRangeH)\r\nVanilla value: 1\r\nValidation: 1–5 casual, 1–10 advanced\r\nWorks with SignCellRangeH (0x3C) and SignCellRangeDown (0x44) to define the full 3D search volume.",
	},
	{
		Key: "signCellRangeDown", View: ViewSign,
		Label: "Cell range (downward)", Internal: "SignCellRangeDown", Type: "int32",
		Advanced: true, Min: 1, Max: 5, AdvancedMin: 1, AdvancedMax: 10,
		ShortDef: "The downward component of the spatial search radius — how many cell layers below the player are included when fetching signs. Most impactful in areas sitting directly above underground regions, where phantoms exploring below would otherwise be invisible to surface hosts.\r\nRaising it → signs from lower floors and underground areas become visible to hosts above them.\r\nLowering it to 1 → only signs from your current vertical cell; players in underground areas beneath you are excluded from your sign pool.",
		LongDef: "The downward counterpart to Cell Range (Upward). While upward range helps hosts find signs from phantoms above them, downward range lets hosts standing at a higher elevation find signs from phantoms in lower areas.\r\n\r\nThe most practically impactful scenario is the surface-to-underground transitions that are common in Elden Ring: Limgrave surface sits directly above Siofra River below; parts of Leyndell connect to underground Leyndell; certain mountain areas sit above deep caves. A host on the surface with downward range of 1 sees only their current vertical cell, meaning phantoms exploring the underground region directly below them are entirely absent from the sign pool.\r\n\r\nRaising downward range opens up those cross-level connections. A host at Limgrave's surface with downward range of 2 can see signs from phantoms one cell layer below — potentially in Siofra River — enabling cross-elevation co-op that the vanilla game doesn't support well.\r\n\r\nFor most areas, setting upward and downward range to the same value makes sense. In specific scenarios where you know your session will be entirely at one altitude level — all underground, all surface — you can tune the ranges asymmetrically to focus the search in the relevant direction.",
		AdvancedDetails: "PARAMDEF SortID: 115 — 召喚サイン取得セル範囲(下方向) (NET_SUMMON_SIGN_PARAM)\r\nMemory offset: 0x44  |  Type: int32 (stored as u32 — same 4-byte storage note as SignCellRangeH)\r\nVanilla value: 1\r\nValidation: 1–5 casual, 1–10 advanced\r\nAll three cell-range parameters (0x3C/0x40/0x44) define a rectangular 3D search volume. Adjust together when increasing overall spatial coverage.",
	},
}

